dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: __token__
  password:
      secure: kK4++8pRgzyQA10Nu045is7fW6mwfZ79zK33ohQZ4HN9VNXhUduI1eh+N5N/6Lfp6iQ/fR2x86ydUbjmq2BYkUCtqTnordnUbhA4yRyJAU3sfmyDOVEwhPod1mLzhVCvFqT4QzcY1b+f94NDRZNB1guBTmEpdSqYIYmrdjwmSwk24O0c2S6rQ4jN7P9MqEPGdb/9kz2DqajWnrJizLSfr2Bsb/Lry1eUoSanLSo+tXK0Z7LHITeiqqmc9YBycvSfEG7KXzIJ2wKgAO5vf3ZyKXKC3KWQHnR+YiC3XjJpnbngccB0EIigB33Ko5cjBaElK2QVgXEL/xn/s5Ic+IcyVZDRue9r01QH6ZoBlq4OwOOU+mKSQCsudq327FB0qKhaXhpK6YUgdGg2xq2LGOr0O16Lqec3zbqeDQ5eWADVJITxX85eSezVqh2uWsP4DConz0DI/g1+G4Imp3A1nTRIxkWbwnq8hiw12zSouyUINQ7wzadKzvdoPwm8JDHVs/I8cTdZXcy2AZOrpI8tTUACMKE9gt8l+XBCb84BaC39zfeCe/u7NERTRn6jva2GN+DM/FNjfbUvyGoi+JApT56NjzRW9MEILb3GqM5P16z3abD1UqAqi34Ix+7jz0ZsHWSkTxJiKShr2XqvA3jHGro+Bs5JwSVyq4jdCeTesEW8kQw=
  distributions: sdist bdist_wheel
  on:
    tags: true