dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: QVrPAUuRxbGLnDjhqzn6V0kHOTyz23cB7C93ErkdQoDWa75iyFYpYV8SkOEl5QM6Jx5u2+ZgfBns75HcGysd8OHAESOeT2ni4+6eCJjjmIgWder52YavgngGFP3hy1vkioSRiIMufyF3L1fT620tjZBYQBVJOdymWf4LzCtMAnYvAMf3hMUFLjN3v1+PUW2oXEjnrHPtUrLknr6JZ4F2HAKvCtNMmy5ORaGihw38PPnJlFC1jH94RzrW3SSC0XoYdhzPi9Yio3tlePubgXe0w8Me+7H0B2mPymph2GE//Lz3GRtiddwlx9IR/lQbbQ5Fq3dnoxKQhLSqXTzxDmrINqdaVMToj94whPuuuQ6+l9BcFfqt8JA7o32QDbCofVCuJC70LSqqF6phy2J4trB6YHslRG3YbH3YDneAbWXu6EYLRo20QfB80mz8SU8rovpB2oKXmpBkpffeFJlQerhjlCgNiHlzAKeWEhmw9wrpWIywDCFZYxuDrOae3HFCkMjkc8I6n6Lk2kayqThBJBs7JDcXGPfAUs7y5JBKOJo78pKuBO/LfXAtRH0etxBebd8ySRGRsDbOhR/h79qaA7NuDEbCfWG7xeJfk8ZcJ3X0ezPnR7SW6SYAMnk+QgpjjpYoGKbTPQYMs9bQwQ2U2zF+CtKidq/1ZdHL8kwy027FUkk=
  distributions: sdist bdist_wheel
  on:
    tags: true
