dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: M2qC/wOUneBGuq4BYeUtN1eWn/qbps7Rf2sb3ACS8Oj5w+9sHAyMPeJGJDfxtN+pOoWTGhZDAw9zB0hzh6SeEV4sYAT532fRHYvZXdwvCafmoCML7ETXT3ZyMItdti3RAZB9G6yHObib2SpROs1tA9yPWWdPdqoSHDQhnKIizWy6hjaUJeLDMCdClcgNpdRAkgur9dJ6bx1exYq0Ts6V6aRh91Yq8pG4cPNxlKWIc0BJ7xlMSf2DMt18jVUqSHBF0Q+mvUEFppqVhr1+sGDlZkemn/8EUL+La+TDkrH6f29e6XW+a9HOLw3A3LFkvQE6rMr/t+mXMMcGjhJDzprSlxOxEaM98EJw4NB5ncFMUSkjzoCRM/OWmu95V9m0r7QB3YKnHv2MfwHD/G53MY7kT/T5oxwjmQ1bIE8cPGf5LQP0rTnBW5gnM+c/3X2IhW5izNvKLhW0Nt7oPgS/nSg3kiMFIyV8vjEMaYIunmKkB7AnjaxsVwb/tK5iDcDQ8UtuB2OM552EbTtJ3csGZisL7TU/370rtR/uhL0Te9vg8himGMu2sTo0xft2ItDgp5ltR8RdmdfWvUSYW4mqmwFq2IrgUl+uxubncwZJ96Vcy++4ZjCPCPlbd1QJhMxBKVUlZE5b7m3JWxr39xMrLEouvJnTTpSz1Zt5y0yZHPunkKM=
  distributions: sdist bdist_wheel
  on:
    tags: true