dist: xenial
language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
script:
    - python -m unittest
deploy:
    provider: pypi
    user: "__token__"
    password: ${KEY}
    on:
        tags: true